site_name: Документация к лабораторной работе №3
nav:
    - Домой: index.md
    - Описание:
        - Описание программной структуры: 1.md
        - Описание СУБД: 2.md
        - Описание таблиц СУБД: 3.md
        - Код создания таблиц: 4.md
        - Код добавления данных: 5.md
theme:
name: THEME_Material